# Add udp service to CP
- name: login
  uri:
    url: "https://192.168.1.100/web_api/v1.6/login"
    validate_certs: false
    method: POST
    body_format: json
    body:
      user: "{{ cp_user }}"
      password: "{{ cp_password }}"
  register: loginoutput

- set_fact:
    sid: "{{ loginoutput.json.sid }}"

- name: add_service
  uri:
    url: "https://192.168.1.100/web_api/v1.6/add-service-udp"
    validate_certs: false
    method: POST
    body_format: json
    headers:
      X-chkp-sid: "{{ sid }}"
    body:
      name: "{{ item.value.name }}"
      port: "{{ item.value.service }}"
      keep-connections-open-after-policy-installation: false
      session-timeout: 0
      match-for-any: true
      color: khaki
      comments: "Geneted by Ansible from the board {{ jira_board }} and case ID {{ jira_case }}"
  register: loginoutput

- name: publish
  uri:
    url: "https://192.168.1.100/web_api/v1.6/publish"
    validate_certs: false
    method: POST
    body_format: json
    headers:
      X-chkp-sid: "{{ sid }}"
    body:
      {}
